import turtle
pashwa = turtle.Turtle()
pashwa.color("#31ff1f", "yellow")
pashwa.begin_fill()
pashwa.forward(50)
pashwa.left(45)
pashwa.forward(50)
pashwa.left(45)
pashwa.forward(50)
pashwa.left(45)
pashwa.forward(50)
pashwa.left(45)
pashwa.forward(50)
pashwa.left(45)
pashwa.forward(50)
pashwa.left(45)
pashwa.forward(50)
pashwa.left(45)
pashwa.forward(50)
pashwa.end_fill()
pashwa.penup()
pashwa.forward(200)
pashwa.pendown()
pashwa.color("#ffa763", "#f3b8ff")
pashwa.begin_fill()
pashwa.forward(50)
pashwa.left(45)
pashwa.forward(50)
pashwa.left(45)
pashwa.forward(50)
pashwa.left(45)
pashwa.forward(50)
pashwa.left(45)
pashwa.forward(50)
pashwa.left(45)
pashwa.forward(50)
pashwa.left(45)
pashwa.forward(50)
pashwa.left(45)
pashwa.forward(50)
pashwa.end_fill()
turtle.done()


